# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.hostname = "aourhzalS"
  aourhzalS.vm.network "private_network", ip: "192.168.56.110"
  config.vm.provider "virtualbox" do |v|
    v.name = "aourhzalS"
  end

  config.vm.provision "shello", inline: <<-SHELL
    sudo apt update
    sudo apt install curl -y
    curl -sfL https://get.k3s.io | sh -
  SHELL
end
