# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "aourhzalS" do |server|
    config.vm.box = "debian/bookworm64"
    config.vm.hostname = "aourhzalS"
    config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provider "virtualbox" do |v|
      v.name = "aourhzalS"
      v.cpus = 2
      v.memory = 1024
    end

    config.vm.provision "shell", inline: <<-SHELL
        sudo apt update
        sudo apt install curl -y
        # Add Docker's official GPG key:
        sudo apt-get update
        sudo apt-get install ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        # Add the repository to Apt sources:
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
          $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
        curl -sfL https://get.k3s.io | sh -s - --docker
      SHELL
  end
end
